<?php

namespace humhub\modules\calendar_extension;

use humhub\modules\calendar_extension\models\CalendarExtensionCalendar;
use humhub\modules\calendar_extension\models\CalendarExtensionCalendarEntry;
use humhub\modules\calendar_extension\models\CalendarExtensionEntry;
use Yii;
use yii\helpers\Url;

class Module extends \humhub\components\Module
{

    /**
     * @inheritdoc
     */
    public $resourcesPath = 'resources';

    /**
     * On Init of Dashboard Sidebar, add the widget
     *
     * @param type $event
     */
    public static function onDashboardSidebarInit($event)
    {
        if (Yii::$app->user->isGuest) {
            return;
        }

        $module = Yii::$app->getModule('calendar_extension');
    }

    /**
     * @inheritdoc
     */
    public function disable()
    {
        foreach (CalendarExtensionCalendar::find()->all() as $entry) {
            $entry->delete();
        }
//        foreach (CalendarExtensionCalendarEntry::find()->all() as $entry) {
//            $entry->delete();
//        }
        parent::disable();
    }

    public function getConfigUrl()
    {
        return Url::to(['/calendar_extension/admin/index']);
    }

    /**
     * @inheritdoc
     */
    public function getPermissions($contentContainer = null)
    {
        if ($contentContainer !== null) {
            return [
                new permissions\AdministerExternalCalendars(),
            ];
        }
        return [];
    }

//    public function getNotifications()
//    {
//        return parent::getNotifications(); // TODO: Change the autogenerated stub
//    }

    /**
     * @inheritdoc
     */
//    public function beforeAction($action)
//    {
//        // Fix prior 1.2.1 without set formatter timeZone
//        // https://github.com/humhub/humhub/commit/3a06a3816131c3c10659b65e70422a8b8bdca15c#diff-6245cc1612ecb552c18a2e5a1d9bbca2c
//        if (empty(Yii::$app->formatter->timeZone)) {
//            Yii::$app->formatter->timeZone = Yii::$app->timeZone;
//        }
//        return parent::beforeAction($action);
//    }


}