<?php

namespace humhub\modules\calendar_extension;

use Yii;
use yii\helpers\Url;
use humhub\modules\calendar_extension\permissions\ManageCalendar;
use humhub\modules\calendar_extension\models\CalendarExtensionCalendar;
use humhub\modules\space\models\Space;
use humhub\modules\user\models\User;
use humhub\modules\content\components\ContentContainerModule;
use humhub\modules\content\components\ContentContainerActiveRecord;



class Module extends ContentContainerModule
{

    /**
     * @inheritdoc
     */
//    public function init()
//    {
//        parent::init();
//        $this->set(CalendarService::class, ['class' => CalendarService::class]);
//    }

    /**
     * @inheritdoc
     */
    public function getContentContainerTypes()
    {
        return [
            Space::className(),
            User::className(),
        ];
    }

    public function enable()
    {
        // check if calendar module is enabled
        if (!Yii::$app->hasModule('calendar') && !isset(Yii::$app->modules['calendar']))
        {
            return;
        }
        return parent::enable(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function disable()
    {
//        foreach (CalendarExtensionCalendarEntry::find()->all() as $entry) {
//            $entry->delete();
//        }
        foreach (CalendarExtensionCalendar::find()->all() as $entry) {
            $entry->delete();
        }
        parent::disable();
    }

    /**
     * @inheritdoc
     */
    public function getContentContainerName(ContentContainerActiveRecord $container)
    {
        return Yii::t('CalendarExtensionModule.base', 'External Calendar');
    }

    /**
     * @inheritdoc
     */
    public function getContentContainerDescription(ContentContainerActiveRecord $container)
    {
        if ($container instanceof Space) {
            return Yii::t('CalendarExtensionModule.base', 'Manage external calendar here.');
        }elseif ($container instanceof User) {
            return Yii::t('CalendarExtensionModule.base', 'Manage external calendar for your profile.');
        }
    }

    /**
     * @inheritdoc
     */
    public function disableContentContainer(ContentContainerActiveRecord $container)
    {
        parent::disableContentContainer($container);
        foreach (CalendarExtensionCalendar::find()->contentContainer($container)->all() as $item) {
            $item->delete();
        }
    }

    /**
     * @inheritdoc
     */
    public $resourcesPath = 'resources';

    /**
     * On Init of Dashboard Sidebar, add the widget
     *
     * @param type $event
     */
    public static function onDashboardSidebarInit($event)
    {
        if (Yii::$app->user->isGuest) {
            return;
        }

        $module = Yii::$app->getModule('calendar_extension');
    }

    public function getConfigUrl()
    {
        return Url::to(['/calendar_extension/admin/index']);
    }

    public function getContentContainerConfigUrl(ContentContainerActiveRecord $container)
    {
        if ($container->permissionManager->can(ManageCalendar::class))
        {
            return $container->createUrl('/calendar_extension/calendar/index');
        }
        else
        {
            return;
        }
    }

    /**
     * @inheritdoc
     */
    public function getPermissions($contentContainer = null)
    {
        if ($contentContainer !== null) {
            return [
                new permissions\ManageCalendar(),
                new permissions\ManageEntry(),
            ];
        }
        return [];
    }

}